### ISSUE TITLE
http://mcclure.pw/demo is a dead link

### ISSUE THREAD

**Issue by ML-Chen** [brmc/django-octopus#2]
It says:

> ### Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
> More information about this error may be available in the server error log.

**Comment by brmc** [comment]
thanks for letting me know. this isn't related to the package itself though. something is wrong with my host. my crons didn't let me know the server was down either

i'll let you know when it's back up.  

also, i haven't worked on this package in years. it should still work, but it could use some improvements.

**Comment by brmc** [comment]
it should be working now
